### PR TITLE
Allow using aliases on YAML configs

### PR DESCRIPTION
**Pull request by xjunior**
Psych 4 loads in safe mode by default. To fix compatibility and allow the use of aliases, we have to explicitly allow them.

### CODE REVIEW

**Comment by kou** [comment]
We want to align with the Rails behavior.
Could you check and share the Rails implementation?

**Comment by xjunior** [comment]
@kou that's how they do to ensure compatibility on [webpacker](https://github.com/rails/webpacker/blob/v5.4.4/lib/webpacker/configuration.rb#L96), which also had this issue until 5.4.3.

**Comment by xjunior** [comment]
> @kou that's how they do to ensure compatibility on [webpacker](https://github.com/rails/webpacker/blob/v5.4.4/lib/webpacker/configuration.rb#L96), which also had this issue until 5.4.3.

https://github.com/rails/webpacker/commit/ceaf826d84230aaadbefdbaaf560d474a96affcc

**Comment by xjunior** [comment]
It would also be interesting to add Railtie specs, but I've tested this fix in my development environment with both ruby versions and it works well.

We've just recently updated to ActiveLdap 7, and we're looking to update from ruby 3.0 to 3.3.5, this is one of our blockers.

**Comment by kou** [comment]
Ah, we should align with Active Record not webpacker.
Could you check how Active Record loads `config/database.yml`?

And could you rebase on main to use `docker compose` not `docker-compose` in CI?

> It would also be interesting to add Railtie specs

What is the "Railtie specs"?

**Comment by xjunior** [comment]
> Ah, we should align with Active Record not webpacker. Could you check how Active Record loads `config/database.yml`?
> 
> And could you rebase on main to use `docker compose` not `docker-compose` in CI?
> 
> > It would also be interesting to add Railtie specs
> 
> What is the "Railtie specs"?

Rails internally uses `ActiveSupport::ConfigurationFile`. I didn't want to go to that extent of change as it could affect different versions of rails as well. I did how rails does internally and changed it to use `unsafe_load`.

**Comment by kou** [comment]
> Rails internally uses `ActiveSupport::ConfigurationFile`.

OK. Then could you use `ActiveSupport::ConfigurationFile`?

> I didn't want to go to that extent of change as it could affect different versions of rails as well.

Affecting different versions of Rails is an expected behavior. Because Active Ldap should work like Active Record as much as possible. 

> I did how rails does internally and changed it to use `unsafe_load`.

We don't want to keep synchronizing with Rails internal implementation manually.

**Comment by xjunior** [comment]
@kou code updated to use ActiveSupport::ConfigurationFile

**Comment by kou** [comment]
Thanks.

**Pull request merged**
