### PR TITLE
Fixed timezone with minutes in generalizedTime string format

### PR DESCRIPTION
**Pull request by nengxu**
https://github.com/activeldap/activeldap/issues/160

### CODE REVIEW

**Comment by nengxu** [comment]
The failed CI #307 seems related to Ruby 2.6 support, not related to this pull request.

**Comment by kou** [comment]
Thanks.

Could you rebase instead of merge on mater?

Could you add a test for this case?

**Comment by kou** [comment]
Could you change the title of this pull request to describe summary without issue number?
"Fixed issue #160" isn't suitable for summary.

**Comment by nengxu** [comment]
@kou Done.

**Comment by kou** [comment]
Thanks.
I've merged.

**Pull request merged**
