### PR TITLE
Add JNDI paged search support

### LINKED ISSUE #169: Implement paged searches with Jndi adapter
https://devdocs.io/openjdk~8/javax/naming/ldap/package-summary

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
Closes #169 

I was able to demonstrate paged searching using the [Forum Systems Online LDAP Test Server](http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/)

```ruby
base_dir = File.expand_path(File.dirname(__FILE__))
top_dir = File.expand_path(File.join(base_dir, ".."))
lib_dir = File.join(top_dir, "lib")
$LOAD_PATH.unshift(File.join __dir__, 'lib')

require 'active_ldap'

class Person < ActiveLdap::Base
  setup_connection host: 'ldap.forumsys.com',
                   port: 389,
                   base: 'dc=example,dc=com',
                   method: :plain,
                   bind_dn: 'cn=read-only-admin,dc=example,dc=com',
                   password: 'password',
                   adapter: 'jndi'

  ldap_mapping dn_attribute: 'uid',
               prefix: '',
               classes: %w[person]
end

puts Person.all(filter: { cn: '*' }, attributes: %w[cn]).map(&:cn)
# ==> found paged results cookie: $
# ==> found paged results cookie: 0
# ==> found paged results cookie: 6
# Isaac Newton
# Albert Einstein
# Nikola Tesla
# Galileo Galilei
# Leonhard Euler
# Carl Friedrich Gauss
# Bernhard Riemann
# Euclid
# read-only-admin
# Test
# Marie Curie
# Alfred Nobel
# Robert Boyle
# Louis Pasteur
# No Group
# FS Training
# FS Training
```

### CODE REVIEW

**Comment by HarlemSquirrel** [comment]
I've removed the debugging `puts`. Not sure the best way to automate testing of this feature.

**Comment by HarlemSquirrel** [comment]
It might also be nice to default page size to 500 which is the [default for OpenLDAP 2.4](https://openldap.org/doc/admin24/limits.html). 
Separately from this PR, it would be nice to configure this at the connection level and/or with search arguments. 
Thoughts, @kou ?

**Comment by kou** [comment]
Thanks!
I'll review this after we merge #170.

**Comment by HarlemSquirrel** [comment]
@kou I merged in the latest master and noticed an issue when setting the paged search control to the global context set by JndiConnector. I think we have to either set the request controls at each operation or use a separate context for searching. I opted for a second context here to avoid possible race conditions between concurrent search and add/delete/modify operations.

**Comment by kou** [comment]
I'll review this in a few weeks.
But I may not be able to do it due to the influence of COVID-19. Sorry.

**Comment by HarlemSquirrel** [comment]
Ok. Stay safe, friend.

**Comment by kou** [comment]
> Not sure the best way to automate testing of this feature.

I've added a test for this.

> It might also be nice to default page size to 500 which is the default for OpenLDAP 2.4.

I want to keep the default value as conservative as possible. If the default value isn't suitable (e.g. too large), the default search will report error. It's not good usability.

> Separately from this PR, it would be nice to configure this at the connection level and/or with search arguments.

It's a good idea.
We should do this in adapter abstraction layer instead of JNDI layer.

> I think we have to either set the request controls at each operation or use a separate context for searching.

I've changed to use `set the request controls at each operation` style. Because one connection isn't shared in multiple threads. This is a Active Ldap design (same as Active Record).

**Comment by kou** [comment]
Merged.
Thanks!

**Pull request merged**
