### PR TITLE
Update JNDI adapter to follow referrals by default

### PR DESCRIPTION
**Pull request by HarlemSquirrel**
I ran in to some issues while exploring OpenLDAP where memberOf was not returning while using JNDI but was returning using net-ldap and the ldapsearch command. I finally narrowed it down to JNDI
not following referrals by default.

Now this JNDI adapter will follow referrals by default like net-ldap and the ruby ldap adapters do here. This can be changed with the follow_referrals connection configurations option.

This also sets alias dereferencing to "never" which aligns with OpenLDAP:
https://git.openldap.org/openldap/openldap/-/blob/OPENLDAP_REL_ENG_2_4/doc/man/man1/ldapsearch.1#L198-207

### CODE REVIEW

**Comment by kou** [comment]
Could you ad a test case for this?

**Comment by HarlemSquirrel** [comment]
I added a new test but I don't think it's really covering this scenario which involves dynamic groups. For that, we would need to enable the [dynlist overlay](https://openldap.org/doc/admin24/overlays.html#Dynamic%20Lists). I'm not sure the best way to set that up for testing.

**Comment by HarlemSquirrel** [comment]
I added a connection test for `:follow_referrals` option

**Comment by kou** [comment]
We can prepare our test OpenLDAP server in https://github.com/activeldap/activeldap/blob/master/dockerfiles/openldap-prepare.sh .

I'll take a look at this in a few weeks.

**Comment by HarlemSquirrel** [comment]
@kou I was able to configure dynamic groups and add a test for one. It failed with JNDI without my changes for follow referrals by default so it seems like a worthy test :smiley_cat:

**Comment by HarlemSquirrel** [comment]
@kou do you have a few minutes to review this? Thanks!

**Comment by kou** [comment]
Sorry for my late work!
I'll do in a week.

**Comment by HarlemSquirrel** [comment]
No problem, thanks for your time as always!

**Comment by kou** [comment]
Thanks!
I've simplified tests and added support for per connection configuration.

**Comment by HarlemSquirrel** [comment]
Thank you! I look forward to the next release! 🙂

**Comment by kou** [comment]
Done!

**Pull request merged**
