### PR TITLE
Patch for Ruby 2.2 compability

### PR DESCRIPTION
**Pull request by benlangfeld**
This PR replaces https://github.com/activeldap/activeldap/pull/135.

### CODE REVIEW

**Comment by kou** [comment]
Thanks!

**Comment by benlangfeld** [comment]
Thank you @kou! Do you intend to release this? Would you let me know when you do?

**Comment by kou** [comment]
I never release a new version from this branch because the series are end of life. Use the branch directly.

**Comment by benlangfeld** [comment]
Oh, that's a shame. I am already using the branch this PR came from, and my goal really was to get back to an official release from rubygems.org. I guess I'll release a namespaced fork of the package instead.

**Comment by kou** [comment]
:<. I've released 3.2.3... I hope that you upgrade your application ASAP...

**Comment by benlangfeld** [comment]
@kou I didn't get a notification that you had commented so I only saw this yesterday. Thank you for the release! I've upgraded in production this morning. Much appreciated.

**Pull request merged**
